export const PUBLICATIONS = {
  offset: 0,
  count: 147315,
  next: 'https://stat.oblgazeta.ru/news/?limit=30&offset=30',
  previous: null,
  results: [
    {
      item: 1,
      url: 'https://oblgazeta.ru/society/dom-sad-ogorod/40138/',
      author: '{\'СТАНИСЛАВ МИЩЕНКО\'}',
      author_photo: null,
      title: 'Какой Покров — такая и зима будет',
      pubdate: '2018-10-12',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '158017',
      rubric: 'Общество'
    },
    {
      item: 2,
      url: 'https://oblgazeta.ru/society/38364/',
      author: '{\'ЕЛЕНА АБРАМОВА\'}',
      author_photo: null,
      title: 'В июне замёрзнем: главный синоптик Уралгидрометцентра сообщил, что лето откладывается',
      pubdate: '2018-05-29',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '151736',
      rubric: 'Общество'
    },
    {
      item: 3,
      url: 'https://oblgazeta.ru/sport/38787/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\', \'ПЁТР КАБАНОВ\', \'ДАНИЛ ПАЛИВОДА\'}',
      author_photo: null,
      title: 'Россия - Испания. Прямая трансляция 1/8 финала ЧМ-2018 по футболу',
      pubdate: '2018-07-01',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '124765',
      rubric: 'Спорт'
    },
    {
      item: 4,
      url: 'https://oblgazeta.ru/news/41269/',
      author: '{\'МАКСИМ ЗАНКОВ\'}',
      author_photo: null,
      title: 'В Госдуму РФ внесён законопроект о сборе грибов и ягод',
      pubdate: '2018-09-18',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '118002',
      rubric: 'Политика'
    },
    {
      item: 5,
      url: 'https://oblgazeta.ru/newage/20534/',
      author: '{\'РЕДАКЦИЯ\'}',
      author_photo: null,
      title: 'В Екатеринбурге состоялся ежегодный Открытый областной фестиваль КВН «Уральская Шызгара» на Кубок губернатора Свердловской области',
      pubdate: '2014-11-22',
      olds: true,
      is_news: false,
      is_pr: null,
      total: '114052',
      rubric: 'Новая эра'
    },
    {
      item: 6,
      url: 'https://oblgazeta.ru/news/45264/',
      author: '{\'ЕВГЕНИЯ СКАЧКОВА\'}',
      author_photo: null,
      title: 'Стал известен точный размер прибавки к пенсии в 2019 году',
      pubdate: '2018-12-27',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '103412',
      rubric: 'Экономика'
    },
    {
      item: 7,
      url: 'https://oblgazeta.ru/news/39131/',
      author: '{\'ОКСАНА ЖИЛИНА\'}',
      author_photo: null,
      title: 'В Нижнем Тагиле ушла из жизни первая жена Владимира Высоцкого',
      pubdate: '2018-07-20',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '76420',
      rubric: 'Культура'
    },
    {
      item: 8,
      url: 'https://oblgazeta.ru/newage/20431/',
      author: '{\'РЕДАКЦИЯ\'}',
      author_photo: null,
      title: 'В Екатеринбурге прошел один из самых крупных косплей-фестивалей Урала',
      pubdate: '2014-11-15',
      olds: true,
      is_news: false,
      is_pr: null,
      total: '76271',
      rubric: 'Новая эра'
    },
    {
      item: 9,
      url: 'https://oblgazeta.ru/news/35307/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: null,
      title: 'Чемпионат мира по фигурному катанию-2018. Женщины. Произвольная программа. Прямая трансляция',
      pubdate: '2018-03-24',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '65291',
      rubric: 'Спорт'
    },
    {
      item: 10,
      url: 'https://oblgazeta.ru/news/41007/',
      author: '{\'ВАЛЕНТИН ТЕТЕРИН\'}',
      author_photo: null,
      title: 'Владимир Путин присвоил четверым актёрам звание заслуженных артистов',
      pubdate: '2018-09-11',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '64670',
      rubric: 'Культура'
    },
    {
      item: 11,
      url: 'https://oblgazeta.ru/news/39795/',
      author: '{\'ТАТЬЯНА БУРДАКОВА\'}',
      author_photo: null,
      title: 'Новый поворот в споре о пенсионной реформе: свежие новости к этому часу',
      pubdate: '2018-08-08',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '63031',
      rubric: 'Общество'
    },
    {
      item: 12,
      url: 'https://oblgazeta.ru/newage/22129/',
      author: '{\'АЛЕКСАНДР ПОНОМАРЁВ\'}',
      author_photo: null,
      title: 'В Свердловской области растёт количество школ  с «двухсменками»',
      pubdate: '2015-02-28',
      olds: true,
      is_news: false,
      is_pr: null,
      total: '60084',
      rubric: 'Новая эра'
    },
    {
      item: 13,
      url: 'https://oblgazeta.ru/society/40740/',
      author: '{\'ЮЛИЯ БАБУШКИНА\'}',
      author_photo: null,
      title: 'ТОП-5 законов, которые вступают в силу с 1 декабря',
      pubdate: '2018-12-01',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '59928',
      rubric: 'Общество'
    },
    {
      item: 14,
      url: 'https://oblgazeta.ru/news/45835/',
      author: '{\'ЛАРИСА ХАЙДАРШИНА\'}',
      author_photo: null,
      title: 'Социальные выплаты пенсионерам будут повышены с 1 февраля',
      pubdate: '2019-01-17',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '54473',
      rubric: 'Общество'
    },
    {
      item: 15,
      url: 'https://oblgazeta.ru/news/42785/',
      author: '{\'ВАЛЕНТИН ТЕТЕРИН\'}',
      author_photo: null,
      title: 'Свердловчанин нашёл в тайнике трофейное оружие времён ВОВ и отнёс его в полицию',
      pubdate: '2018-10-27',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '50072',
      rubric: 'Общество'
    },
    {
      item: 16,
      url: 'https://oblgazeta.ru/sport/38567/',
      author: '{\'ЕВГЕНИЙ ЯЧМЕНЁВ\'}',
      author_photo: null,
      title: 'Почему Черчесов отдавал честь Дзюбе?',
      pubdate: '2018-06-15',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '48070',
      rubric: 'Спорт'
    },
    {
      item: 17,
      url: 'https://oblgazeta.ru/news/30920/',
      author: '{\'ОКСАНА ЖИЛИНА\'}',
      author_photo: null,
      title: 'Синоптики рассказали "ОГ", когда на Среднем Урале установится постоянный снежный покров',
      pubdate: '2017-11-14',
      olds: true,
      is_news: true,
      is_pr: null,
      total: '47109',
      rubric: 'Общество'
    },
    {
      item: 18,
      url: 'https://oblgazeta.ru/sport/figure-skating/41769/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: '{}',
      title: 'Девушки. Короткая программа. Прямая трансляция чемпионата мира среди юниоров по фигурному катанию',
      pubdate: '2019-03-07',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '44806',
      rubric: 'Спорт'
    },
    {
      item: 19,
      url: 'https://oblgazeta.ru/sport/figure-skating/40985/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: null,
      title: 'Женщины. Прямая трансляция короткой программы чемпионата России по фигурному катанию',
      pubdate: '2018-12-21',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '43146',
      rubric: 'Спорт'
    },
    {
      item: 20,
      url: 'https://oblgazeta.ru/news/44648/',
      author: '{\'МАКСИМ ЗАНКОВ\'}',
      author_photo: null,
      title: 'В Госдуме РФ поддержали законопроект о сборе грибов и ягод',
      pubdate: '2018-12-12',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '42465',
      rubric: 'Общество'
    },
    {
      item: 21,
      url: 'https://oblgazeta.ru/newage/18311/',
      author: '{\'АЛЕКСАНДР ПОНОМАРЁВ\'}',
      author_photo: null,
      title: 'В Екатеринбурге прошёл турнир по экстремальным видам спорта «УрФУ X-Games»',
      pubdate: '2014-06-21',
      olds: true,
      is_news: false,
      is_pr: null,
      total: '42358',
      rubric: 'Новая эра'
    },
    {
      item: 22,
      url: 'https://oblgazeta.ru/sport/figure-skating/41607/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: '{}',
      title: 'Женщины. Короткая программа. Прямая трансляция финала Кубка России',
      pubdate: '2019-02-21',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '41941',
      rubric: 'Спорт'
    },
    {
      item: 23,
      url: 'https://oblgazeta.ru/news/41466/',
      author: '{\'НИНА ГЕОРГИЕВА\'}',
      author_photo: null,
      title: 'Екатеринбурженка может стать девушкой Playboy-2018',
      pubdate: '2018-09-24',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '41223',
      rubric: 'Общество'
    },
    {
      item: 24,
      url: 'https://oblgazeta.ru/news/46825/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: '{}',
      title: 'Финал Кубка России по фигурному катанию-2019: расписание, трансляции, участники',
      pubdate: '2019-02-12',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '40274',
      rubric: 'Спорт'
    },
    {
      item: 25,
      url: 'https://oblgazeta.ru/sport/figure-skating/41936/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: '{}',
      title: 'Женщины. Произвольная программа. Прямая трансляция чемпионата мира по фигурному катанию в Сайтаме',
      pubdate: '2019-03-22',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '40103',
      rubric: 'Спорт'
    },
    {
      item: 26,
      url: 'https://oblgazeta.ru/sport/bandy/41375/',
      author: '{\'ЕВГЕНИЙ ЯЧМЕНЁВ\'}',
      author_photo: '{}',
      title: 'От конфуза сборную России по хоккею с мячом спас Ишкельдин',
      pubdate: '2019-01-31',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '39355',
      rubric: 'Спорт'
    },
    {
      item: 27,
      url: 'https://oblgazeta.ru/news/37898/',
      author: '{\'ОКСАНА ЖИЛИНА\'}',
      author_photo: null,
      title: 'Оргкомитет ЧМ-2018 разбирается в причинах низкой явки на матч в Екатеринбурге',
      pubdate: '2018-06-16',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '38545',
      rubric: 'Спорт'
    },
    {
      item: 28,
      url: 'https://oblgazeta.ru/sport/figure-skating/41263/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: null,
      title: 'Женщины. Короткая программа. Прямая трансляция чемпионата Европы по фигурному катанию в Минске',
      pubdate: '2019-01-23',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '38241',
      rubric: 'Спорт'
    },
    {
      item: 29,
      url: 'https://oblgazeta.ru/sport/figure-skating/40675/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: null,
      title: 'Женщины. Произвольная программа.Прямая трансляция Гран-при Франции',
      pubdate: '2018-11-25',
      olds: false,
      is_news: false,
      is_pr: null,
      total: '36267',
      rubric: 'Спорт'
    },
    {
      item: 30,
      url: 'https://oblgazeta.ru/news/35173/',
      author: '{\'ЯНА БЕЛОЦЕРКОВСКАЯ\', \'НАТАЛЬЯ ШАДРИНА\'}',
      author_photo: null,
      title: 'Чемпионат мира по фигурному катанию-2018. Женщины. Короткая программа. Прямая трансляция',
      pubdate: '2018-03-21',
      olds: false,
      is_news: true,
      is_pr: null,
      total: '35931',
      rubric: 'Спорт'
    }
  ]
};
